name: 🐞 Bug Report
description: Help us enhance our app by reporting bugs.
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - akionii
  - trying559
body:
  - type: input
    id: bug-description
    attributes:
      label: Bug Description
      description: Describe the bug in a clear and concise manner.
      placeholder: "Example: The video player fails to load..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Detail the steps to reproduce the issue.
      placeholder: "1. Go to '...'\n2. Click on '...'\n3. See error"
    validations:
      required: true

  - type: textarea
    id: expected-vs-actual
    attributes:
      label: Expected vs Actual Behavior
      description: Describe what you expected to happen and what actually happened.
      placeholder: "Expected: The video plays smoothly.\nActual: The video fails to load."
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Add any other context or screenshots about the problem here.
      placeholder: "Example: This issue occurs only on Chrome..."
    validations:
      required: false

  - type: markdown
    attributes:
      value: "Thank you for contributing to our project by submitting a bug report!"

  - type: input
    id: contact-info
    attributes:
      label: Contact Information (Optional)
      description: Provide your email if you're open to follow-up questions.
      placeholder: "example@email.com"

  - type: dropdown
    id: app-version
    attributes:
      label: App Version
      description: Select the version of the app where you encountered the bug.
      options:
        - 0.3.5
        - 0.3.4
        - 0.3.3
        - 0.3.2
        - 0.3.1
        - 0.3.0
        - 0.2.1
        - 0.2.0
        - 0.1.0 
      default: 0
    validations:
      required: true

  - type: dropdown
    id: browsers-affected
    attributes:
      label: Browsers Affected
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge

  - type: textarea
    id: logs
    attributes:
      label: Logs (if applicable)
      description: Include any relevant log output.
      render: shell

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
